require('config.opts')
require('config.keymaps')
require('config.autocmds')

require('modules.mini')
require('modules.sources')
require('modules.lsp')
require('modules.path')
require('modules.picker')

require('plugins.fff')
require('plugins.grug-far')
require('plugins.treesitter')
require('plugins.blink')
require('plugins.conform')
require('plugins.rustaceanvim')
