vim.keymap.set({ 'n', 'x', 'i' }, '<c-s>', '<esc><cmd>w<cr><esc>')
vim.keymap.set({ 'n', 'x', 'i' }, '<esc>', '<esc><cmd>noh<cr><esc>')

vim.keymap.set({ 'n', 'x' }, 'j', [[v:count == 0 ? 'gj' : 'j']], { expr = true })
vim.keymap.set({ 'n', 'x' }, 'k', [[v:count == 0 ? 'gk' : 'k']], { expr = true })

vim.keymap.set('x', 'p', 'P')

vim.keymap.set('n', 'Y', 'v$<left>y')
vim.keymap.set('n', '<c-d>', '<c-d>zz')
vim.keymap.set('n', '<c-u>', '<c-u>zz')
vim.keymap.set('n', 'n', 'nzzzv')
vim.keymap.set('n', 'N', 'Nzzzv')
vim.keymap.set('n', '*', '*zzzv')
vim.keymap.set('n', '#', '#zzzv')

vim.keymap.set('t', '<esc><esc>', '<c-\\><c-n>')
vim.keymap.set('t', '<C-h>', '<cmd>wincmd h<cr>')
vim.keymap.set('t', '<C-j>', '<cmd>wincmd j<cr>')
vim.keymap.set('t', '<C-k>', '<cmd>wincmd k<cr>')
vim.keymap.set('t', '<C-l>', '<cmd>wincmd l<cr>')
vim.keymap.set('t', '<C-/>', '<cmd>close<cr>')
vim.keymap.set('t', '<c-_>', '<cmd>close<cr>')

vim.keymap.set('x', '<', '<gv')
vim.keymap.set('x', '>', '>gv')
vim.keymap.set('n', '<', '<cmd>bn<cr>')
vim.keymap.set('n', '>', '<cmd>bp<cr>')

vim.keymap.set('n', '<c-h>', '<c-w>h')
vim.keymap.set('n', '<c-j>', '<c-w>j')
vim.keymap.set('n', '<c-k>', '<c-w>k')
vim.keymap.set('n', '<c-l>', '<c-w>l')
vim.keymap.set('n', '<c-up>', '<cmd>resize +5<cr>')
vim.keymap.set('n', '<c-down>', '<cmd>resize -5<cr>')
vim.keymap.set('n', '<c-left>', '<cmd>vertical resize -20<cr>')
vim.keymap.set('n', '<c-right>', '<cmd>vertical resize +20<cr>')
vim.keymap.set('n', '<c-w>+', '<cmd>resize +5<cr>')
vim.keymap.set('n', '<c-w>-', '<cmd>resize -5<cr>')
vim.keymap.set('n', '<c-w><', '<cmd>vertical resize -20<cr>')
vim.keymap.set('n', '<c-w>>', '<cmd>vertical resize +20<cr>')
vim.keymap.set('n', '-', '<cmd>Ex<cr>')

vim.keymap.set('n', ']t', '<cmd>tabnext<cr>', { desc = 'next tab' })
vim.keymap.set('n', '[t', '<cmd>tabprevious<cr>', { desc = 'previous tab' })
vim.keymap.set('n', '[T', '<cmd>tabfirst<cr>', { desc = 'first tab' })
vim.keymap.set('n', ']T', '<cmd>tablast<cr>', { desc = 'last tab' })

vim.keymap.set('n', '<leader><tab>o', '<cmd>tabonly<cr>', { desc = 'close other tabs' })
vim.keymap.set('n', '<leader><tab><tab>', '<cmd>tabnew<cr>', { desc = 'new tab' })
vim.keymap.set('n', '<leader><tab>c', '<cmd>tabclose<cr>', { desc = 'close tab' })
