set('x', 'p', 'p')
set({ 'n', 'v', 'i' }, '<esc>', '<esc><cmd>nohl<cr><esc>')
set('n', '<c-d>', '<c-d>zz')
set('n', '<c-u>', '<c-u>zz')
set({ 'n', 'x' }, 'j', [[v:count == 0 ? 'gj' : 'j']], { expr = true })
set({ 'n', 'x' }, 'k', [[v:count == 0 ? 'gk' : 'k']], { expr = true })
set({ 'n', 'i', 'x' }, '<c-s>', '<esc><cmd>w<cr><esc>')
set('n', '<c-h>', '<c-w>h')
set('n', '<c-j>', '<c-w>j')
set('n', '<c-k>', '<c-w>k')
set('n', '<c-l>', '<c-w>l')
set('n', '<c-up>', '<cmd>resize +5<cr>')
set('n', '<c-down>', '<cmd>resize -5<cr>')
set('n', '<c-left>', '<cmd>vertical resize -20<cr>')
set('n', '<c-right>', '<cmd>vertical resize +20<cr>')
