local s = vim.keymap.set

s({ 'n', 'x', 'i' }, '<c-s>', '<esc><cmd>w<cr><esc>')
s({ 'n', 'x', 'i' }, '<esc>', '<esc><cmd>noh<cr><esc>')
s({ 'n', 'x' }, 'j', [[v:count == 0 ? 'gj' : 'j']], { expr = true })
s({ 'n', 'x' }, 'k', [[v:count == 0 ? 'gk' : 'k']], { expr = true })
s('x', 'p', 'P')
s('n', 'Y', 'v$<left>y')
s('n', '<c-d>', '<c-d>zz')
s('n', '<c-u>', '<c-u>zz')
s('x', '<', '<gv')
s('x', '>', '>gv')
s('n', '<c-h>', '<c-w>h')
s('n', '<c-j>', '<c-w>j')
s('n', '<c-k>', '<c-w>k')
s('n', '<c-l>', '<c-w>l')
s('n', '<c-up>', '<cmd>resize +5<cr>')
s('n', '<c-down>', '<cmd>resize -5<cr>')
s('n', '<c-left>', '<cmd>vertical resize -20<cr>')
s('n', '<c-right>', '<cmd>vertical resize +20<cr>')
s('n', '-', '<cmd>Oil<CR>', { desc = 'oil' })
s('n', '<leader>db', function() require('dap').toggle_breakpoint() end, { desc = 'Toggle Breakpoint' })
s('n', '<leader>dc', function() require('dap').continue() end, { desc = 'Continue' })
s('n', '<leader>dt', function() require('dap').terminate() end, { desc = 'Terminate' })
s('n', '<leader>dw', function() require('dap.ui.widgets').hover() end, { desc = 'Widgets' })
s('n', '<leader>fb', function() require('fzf-lua').buffers() end, { desc = 'Buffers' })
s('n', '<leader>ff', function() require('fzf-lua').files() end, { desc = 'Files' })
s('n', '<leader>fo', function() require('fzf-lua').oldfiles() end, { desc = 'Oldfiles' })
s('n', '<leader>fq', function() require('fzf-lua').quickfix() end, { desc = 'Qf' })
s('n', '<leader>fl', function() require('fzf-lua').blines() end, { desc = 'Lines' })
s('n', '<leader>ft', function() require('fzf-lua').tabs() end, { desc = 'Tabs' })
s('n', '<leader>fg', function() require('fzf-lua').live_grep() end, { desc = 'Lgrep' })
s('n', '<leader>fG', function() require('fzf-lua').live_grep_glob() end, { desc = 'Lgrep glob' })
s('x', '<leader>fg', function() require('fzf-lua').grep_visual() end, { desc = 'Lgrep visual' })
s('n', '<leader>fr', function() require('fzf-lua').live_grep_resume() end, { desc = 'Lgrep resume' })
