-- https://github.com/mhinz/vim-galore#saner-behavior-of-n-and-n
Utils.Set('n', 'n', "'Nn'[v:searchforward].'zv'", { expr = true })
Utils.Set('x', 'n', "'Nn'[v:searchforward]", { expr = true })
Utils.Set('o', 'n', "'Nn'[v:searchforward]", { expr = true })
Utils.Set('n', 'N', "'nN'[v:searchforward].'zv'", { expr = true })
Utils.Set('x', 'N', "'nN'[v:searchforward]", { expr = true })
Utils.Set('o', 'N', "'nN'[v:searchforward]", { expr = true })
Utils.Set('i', ',', ',<C-g>u')
Utils.Set('i', '.', '.<C-g>u')
Utils.Set('i', ';', ';<C-g>u')
Utils.Set('x', 'p', 'P')
Utils.Set({ 'n', 'x' }, 'j', [[v:count == 0 ? 'gj' : 'j']], { expr = true })
Utils.Set({ 'n', 'x' }, 'k', [[v:count == 0 ? 'gk' : 'k']], { expr = true })
Utils.Set({ 'n', 'x', 'i' }, '<Esc>', '<Esc><Cmd>nohl<CR><Esc>')
Utils.Set('n', '<C-h>', '<C-w>h')
Utils.Set('n', '<C-j>', '<C-w>j')
Utils.Set('n', '<C-k>', '<C-w>k')
Utils.Set('n', '<C-l>', '<C-w>l')
Utils.Set('n', '<C-w>+', '<Cmd>resize +5<CR>', { remap = true })
Utils.Set('n', '<C-w>-', '<Cmd>resize -5<CR>', { remap = true })
Utils.Set('n', '<C-w><', '<Cmd>vertical resize -20<CR>', { remap = true })
Utils.Set('n', '<C-w>>', '<Cmd>vertical resize +20<CR>', { remap = true })
Utils.Set('n', '<C-Up>', '<Cmd>resize +5<CR>', { remap = true })
Utils.Set('n', '<C-Down>', '<Cmd>resize -5<CR>', { remap = true })
Utils.Set('n', '<C-Left>', '<Cmd>vertical resize -20<CR>', { remap = true })
Utils.Set('n', '<C-Right>', '<Cmd>vertical resize +20<CR>', { remap = true })
Utils.Set({ 'n', 'i', 'x' }, '<C-s>', '<Esc><Cmd>w<CR><Esc>')
Utils.Set('x', '>', '>gv')
Utils.Set('x', '<', '<gv')
