local add, now, later = MiniDeps.add, MiniDeps.now, MiniDeps.later

now(function() add({ name = 'mini.nvim' }) end)
now(function() vim.cmd('colorscheme minigrey') end)

now(Plugins.mininotify)
now(Plugins.miniicons)

later(function() vim.ui.select = require('mini.pick').ui_select end)

later(function() require('mini.doc').setup() end)
later(function() require('mini.align').setup() end)
later(function() require('mini.operators').setup() end)
later(function() require('mini.diff').setup({ view = { style = 'sign' } }) end)

later(function()
  add({ source = 'nvim-lua/plenary.nvim' })
  add({ source = 'lambdalisue/vim-suda' })
  add({ source = 'HakonHarnes/img-clip.nvim' })
  add({ source = 'tpope/vim-sleuth' })
  add({ source = 'tpope/vim-fugitive' })
  add({ source = 'junegunn/fzf', hooks = Hooks.fzf })
  add({ source = 'iamcco/markdown-preview.nvim', hooks = Hooks.mkdp })
  add({ source = 'nvim-treesitter/nvim-treesitter', hooks = Hooks.treesitter })
  add({ source = 'mfussenegger/nvim-lint' })
  add({ source = 'williamboman/mason.nvim', hooks = Hooks.mason })
  add({ source = 'kevinhwang91/nvim-bqf' })
  add({ source = 'saghen/blink.compat' })
  add({ source = 'Saghen/blink.cmp', hooks = Hooks.blink })
  add({ source = 'olimorris/codecompanion.nvim' })
  add({ source = 'stevearc/conform.nvim' })
  add({ source = 'neovim/nvim-lspconfig' })
  add({ source = 'theHamsta/nvim-dap-virtual-text' })
  add({ source = 'mfussenegger/nvim-dap' })
  add({ source = 'mfussenegger/nvim-dap-python' })
  add({ source = 'kevinhwang91/promise-async' })
  add({ source = 'chrisgrieser/nvim-origami' })
  add({ source = 'kevinhwang91/nvim-ufo' })
  add({ source = 'hrsh7th/nvim-deck' })
  add({ source = 'Vigemus/iron.nvim' })
end)

later(Plugins.csvview)
later(Plugins.minifiles)
later(Plugins.treesitter)
later(Plugins.nvim_lint)
later(Plugins.mason)
later(Plugins.bqf)
later(Plugins.blink)
later(Plugins.codecompanion)
later(Plugins.conform)
later(Plugins.lspconfig)
later(Plugins.dap)
later(Plugins.ufo)
later(Plugins.nvim_deck)
later(Plugins.iron)

later(Plugins.miniclue)
