Config.now(function() require('crnvl.plug._kanagawa') end)

Config.now_if_args(function() require('crnvl.plug._schemastore') end)
Config.now_if_args(function() require('crnvl.plug._sleuth') end)
Config.now_if_args(function() require('crnvl.plug._ts-autotag') end)
Config.now_if_args(function() require('crnvl.plug._ts-comments') end)

Config.now_if_args(function() require('crnvl.plug._image') end)
Config.now_if_args(function() require('crnvl.plug._img-clip') end)
Config.now_if_args(function() require('crnvl.plug._markdown-preview') end)
Config.now_if_args(function() require('crnvl.plug._typst-preview') end)

Config.now_if_args(function() require('crnvl.plug._conform') end)
Config.now_if_args(function() require('crnvl.plug._lspconfig') end)
Config.now_if_args(function() require('crnvl.plug._treesitter') end)
Config.now_if_args(function() require('crnvl.plug._codediff') end)
Config.now_if_args(function() require('crnvl.plug._grug-far') end)

Config.now_if_args(function() require('crnvl.plug._mini-ai') end)
Config.now_if_args(function() require('crnvl.plug._mini-align') end)
Config.now_if_args(function() require('crnvl.plug._mini-bufremove') end)
Config.now_if_args(function() require('crnvl.plug._mini-clue') end)
Config.now_if_args(function() require('crnvl.plug._mini-cmdline') end)
Config.now_if_args(function() require('crnvl.plug._mini-completion') end)
Config.now_if_args(function() require('crnvl.plug._mini-files') end)
Config.now_if_args(function() require('crnvl.plug._mini-hipatterns') end)
Config.now_if_args(function() require('crnvl.plug._mini-indentscope') end)
Config.now_if_args(function() require('crnvl.plug._mini-jump2d') end)
Config.now_if_args(function() require('crnvl.plug._mini-keymap') end)
Config.now_if_args(function() require('crnvl.plug._mini-move') end)
Config.now_if_args(function() require('crnvl.plug._mini-operators') end)
Config.now_if_args(function() require('crnvl.plug._mini-pairs') end)
Config.now_if_args(function() require('crnvl.plug._mini-pick') end)
Config.now_if_args(function() require('crnvl.plug._mini-snippets') end)
Config.now_if_args(function() require('crnvl.plug._mini-splitjoin') end)
Config.now_if_args(function() require('crnvl.plug._mini-surround') end)
Config.now_if_args(function() require('crnvl.plug._mini-statusline') end)
Config.now_if_args(function() require('crnvl.plug._mini-bracketed') end)
Config.now_if_args(function() require('crnvl.plug._mini-git') end)
Config.now_if_args(function() require('crnvl.plug._mini-diff') end)
