Config.now(function() require('plug.tokyonight') end)
Config.now(function() require('plug.mini-icons') end)

Config.now_if_args(function() require('plug.schemastore') end)
Config.now_if_args(function() require('plug.sleuth') end)
Config.now_if_args(function() require('plug.fugitive') end)
Config.now_if_args(function() require('plug.lualine') end)
Config.now_if_args(function() require('plug.ts-autotag') end)
Config.now_if_args(function() require('plug.ts-comments') end)
Config.now_if_args(function() require('plug.grug-far') end)
Config.now_if_args(function() require('plug.image') end)
Config.now_if_args(function() require('plug.img-clip') end)
Config.now_if_args(function() require('plug.markdown-preview') end)
Config.now_if_args(function() require('plug.typst-preview') end)
Config.now_if_args(function() require('plug.treesitter') end)
Config.now_if_args(function() require('plug.lspconfig') end)
Config.now_if_args(function() require('plug.conform') end)

Config.later(function() require('plug.mini-bufremove') end)
Config.later(function() require('plug.mini-indentscope') end)
Config.later(function() require('plug.mini-completion') end)
Config.later(function() require('plug.mini-hipatterns') end)
Config.later(function() require('plug.mini-jump2d') end)
Config.later(function() require('plug.mini-pairs') end)
Config.later(function() require('plug.mini-ai') end)
Config.later(function() require('plug.mini-keymap') end)
Config.later(function() require('plug.mini-snippets') end)
Config.later(function() require('plug.mini-files') end)
Config.later(function() require('plug.mini-pick') end)
Config.later(function() require('plug.mini-clue') end)

Config.later(function() require('mini.align').setup() end)
Config.later(function() require('mini.operators').setup() end)
Config.later(function() require('mini.move').setup() end)
Config.later(function() require('mini.surround').setup() end)
Config.later(function() require('mini.splitjoin').setup() end)
Config.later(function() require('mini.cmdline').setup() end)
