local nx = { 'n', 'x' }
local nt = { 'n', 't' }
local nix = { 'n', 'i', 'x' }

Config.set(nx, 'j', [[v:count == 0 ? 'gj' : 'j']], { expr = true, desc = 'Go down one visual line' })
Config.set(nx, 'k', [[v:count == 0 ? 'gk' : 'k']], { expr = true, desc = 'Go up one visual line' })
Config.set(nt, '<C-Left>', '<Cmd>vertical resize -20<CR>', { noremap = true, desc = 'Decrease window width' })
Config.set(nt, '<C-Down>', '<Cmd>resize -5<CR>', { noremap = true, desc = 'Decrease window height' })
Config.set(nt, '<C-Up>', '<Cmd>resize +5<CR>', { noremap = true, desc = 'Increase window height' })
Config.set(nt, '<C-Right>', '<Cmd>vertical resize +20<CR>', { noremap = true, desc = 'Increase window width' })
Config.set(nix, '<Esc>', '<Esc><Cmd>noh<CR><Esc>', { noremap = true, desc = 'Clear hlsearch on <Esc>' })
Config.set('n', 'Y', 'yg_', { noremap = true, desc = 'Yank till end of current line' })
Config.set('x', 'p', 'P', { noremap = true, desc = 'Paste in visual mode without overriding register' })
Config.set('x', '>', '>gv', { desc = 'Indent' })
Config.set('x', '<', '<gv', { desc = 'Deindent' })
Config.set('n', '<C-h>', '<C-w>h', { noremap = true, desc = 'Go to left window' })
Config.set('n', '<C-j>', '<C-w>j', { noremap = true, desc = 'Go to window below' })
Config.set('n', '<C-k>', '<C-w>k', { noremap = true, desc = 'Go to window above' })
Config.set('n', '<C-l>', '<C-w>l', { noremap = true, desc = 'Go to right window' })
Config.set('n', '<C-d>', '<C-d>zz', { noremap = true, desc = 'Scroll down' })
Config.set('n', '<C-u>', '<C-u>zz', { noremap = true, desc = 'Scroll up' })
Config.set('c', '<C-f>', '<Right>', { noremap = true, desc = 'Move cursor to the right char' })
Config.set('c', '<C-b>', '<Left>', { noremap = true, desc = 'Move cursor to the left char' })
Config.set('c', '<C-a>', '<Home>', { noremap = true, desc = 'Move cursor to start of line' })
Config.set('c', '<C-e>', '<End>', { noremap = true, desc = 'Move cursor to end of line' })
Config.set('c', '<C-g>', '<C-c>', { noremap = true, desc = 'Quit/Exit from cmdline' })
Config.set('c', '<M-h>', '<C-f>', { noremap = true, desc = 'Access cmdline history' })
Config.set('c', '<M-f>', '<C-Right>', { noremap = true, desc = 'Move cursor to left word' })
Config.set('c', '<M-b>', '<C-Left>', { noremap = true, desc = 'Move cursor to right word' })
Config.set('n', '<C-h>', '<Cmd>TmuxNavigateLeft<CR>', { noremap = true, desc = 'Go to left window' })
Config.set('n', '<C-j>', '<Cmd>TmuxNavigateDown<CR>', { noremap = true, desc = 'Go to window below' })
Config.set('n', '<C-k>', '<Cmd>TmuxNavigateUp<CR>', { noremap = true, desc = 'Go to window above' })
Config.set('n', '<C-l>', '<Cmd>TmuxNavigateRight<CR>', { noremap = true, desc = 'Go to right window' })
Config.set('n', 'E', '<Cmd>lua vim.diagnostic.open_float()<CR>', { desc = 'Open Current Diagnostic' })
Config.set('n', 'grd', '<Cmd>lua vim.lsp.buf.definition()<CR>', { desc = 'vim.lsp.buf.definition()' })
Config.set('n', 'grD', '<Cmd>lua vim.diagnostic.setqflist()<CR>', { desc = 'vim.diagnostic.setqflist()' })
Config.set('n', '<leader>ef', '<Cmd>Dirvish<CR>', { desc = 'File explorer' })
Config.set('n', '<leader>ff', ':find<space>', { desc = 'Fuzzy find' })
Config.set('n', '<leader>fg', ":sil<space>grep<space>''<left>", { desc = 'Fuzzy find file' })
Config.set('n', '<leader>fh', ':help<space>', { desc = 'Fuzzy find file' })
Config.set('n', '<leader>fl', function()
  local file = vim.fn.getreg('%')
  local left = vim.api.nvim_replace_termcodes('<Left>', true, false, true)
  vim.api.nvim_feedkeys(":sil grep '' -g=" .. file .. string.rep(left, 5 + #file), 'n', false)
end, { desc = 'Grep current file' })
Config.set('n', '<Leader>uc', '<Cmd>setlocal cursorline! cursorline?<CR>', { desc = "Toggle 'cursorline'" })
Config.set('n', '<Leader>uC', '<Cmd>setlocal cursorcolumn! cursorcolumn?<CR>', { desc = "Toggle 'cursorcolumn'" })
Config.set('n', '<Leader>ud', '<Cmd>lua print(M.toggle_diagnostic())<CR>', { desc = 'Toggle diagnostic' })
Config.set('n', '<Leader>uf', '<Cmd>lua print("No formatter configured for this ft")<CR>', { desc = 'Format file' })
Config.set('n', '<Leader>uF', '<Cmd>lua print("No formatter configured for this ft")<CR>', { desc = 'Format project' })
Config.set('n', '<Leader>ui', '<Cmd>setlocal ignorecase! ignorecase?<CR>', { desc = "Toggle 'ignorecase'" })
Config.set('n', '<Leader>ul', '<Cmd>setlocal list! list?<CR>', { desc = "Toggle 'list'" })
Config.set('n', '<Leader>un', '<Cmd>setlocal number! number?<CR>', { desc = "Toggle 'number'" })
Config.set('n', '<Leader>ur', '<Cmd>setlocal relativenumber! relativenumber?<CR>', { desc = "Toggle 'relativenumber'" })
Config.set('n', '<Leader>us', '<Cmd>setlocal spell! spell?<CR>', { desc = "Toggle 'spell'" })
Config.set('n', '<Leader>uw', '<Cmd>setlocal wrap! wrap?<CR>', { desc = "Toggle 'wrap'" })
