require('plugins.grug-far')
require('plugins.treesitter')
require('plugins.blink')
require('plugins.codecompanion')
require('plugins.conform')
require('plugins.crates')
require('plugins.rustacenvim')
require('plugins.neoterm')
