local add = MiniDeps.add

add({ source = 'nvim-treesitter/nvim-treesitter', hooks = { post_update = function() vim.cmd('TSUpdate') end } })
add({ source = 'williamboman/mason.nvim', hooks = { post_checkout = function() vim.cmd('MasonUpdate') end } })
add({ source = 'junegunn/fzf', hooks = { post_checkout = function() vim.fn['fzf#install']() end } })
-- add({ source = 'EdenEast/nightfox.nvim' })
add({ source = 'phha/zenburn.nvim' })
add({ source = 'nvim-lua/plenary.nvim' })
add({ source = 'nvim-neotest/nvim-nio' })
add({ source = 'williamboman/mason-lspconfig.nvim' })
add({ source = 'WhoIsSethDaniel/mason-tool-installer.nvim' })
add({ source = 'theHamsta/nvim-dap-virtual-text' })
add({ source = 'rcarriga/nvim-dap-ui' })
add({ source = 'leoluz/nvim-dap-go' })
add({ source = 'mfussenegger/nvim-dap' })
add({ source = 'jay-babu/mason-nvim-dap.nvim' })
add({ source = 'MagicDuck/grug-far.nvim' })
add({ source = 'stevearc/oil.nvim' })
add({ source = 'ibhagwan/fzf-lua' })
add({ source = 'tpope/vim-fugitive' })
add({ source = 'tpope/vim-rhubarb' })
add({ source = 'lewis6991/gitsigns.nvim' })
add({ source = 'hrsh7th/cmp-buffer' })
add({ source = 'hrsh7th/cmp-path' })
add({ source = 'hrsh7th/cmp-nvim-lua' })
add({ source = 'hrsh7th/cmp-nvim-lsp' })
add({ source = 'hrsh7th/nvim-cmp' })
add({ source = 'neovim/nvim-lspconfig' })
add({ source = 'stevearc/conform.nvim' })
add({ source = 'stevearc/quicker.nvim' })
add({ source = 'kevinhwang91/nvim-bqf' })
add({ source = 'nvim-treesitter/nvim-treesitter-textobjects' })
add({ source = 'DrKJeff16/project.nvim' })
add({ source = 'NeogitOrg/neogit' })
add({ source = 'sindrets/diffview.nvim' })
