vim.keymap.set('n', '<Leader>uf', function()
  local file = vim.fn.getreg('%')
  vim.cmd('silent !stylua ' .. file)
  vim.cmd('edit')
end, { desc = 'Format file', buffer = true })

vim.keymap.set('n', '<Leader>uF', function()
  vim.cmd('silent !stylua .')
  vim.cmd('edit')
end, { desc = 'Format project', buffer = true })
