vim.keymap.set('n', '<Leader>uf', function()
  local file = vim.fn.getreg('%')
  vim.cmd([[silent! update | redraw]])
  vim.cmd('silent !uv run --all-groups ruff format ' .. file)
  vim.notify('Format: ' .. file)
end, { desc = 'Format file', buffer = true })

vim.keymap.set('n', '<Leader>uF', function()
  vim.cmd([[silent! update | redraw]])
  vim.cmd('silent !uv run --all-groups ruff format')
  vim.notify('Format: Project')
end, { desc = 'Format project', buffer = true })
