return {
  { mode = 'n', keys = '<Leader>' },
  { mode = 'x', keys = '<Leader>' },
  { mode = 'n', keys = '<Localleader>' },
  { mode = 'x', keys = '<Localleader>' },
  { mode = 'n', keys = [[\]] },
  { mode = 'n', keys = '[' },
  { mode = 'x', keys = '[' },
  { mode = 'n', keys = ']' },
  { mode = 'x', keys = ']' },
  { mode = 'i', keys = '<C-x>' },
  { mode = 'n', keys = 'g' },
  { mode = 'x', keys = 'g' },
  { mode = 'n', keys = "'" },
  { mode = 'x', keys = "'" },
  { mode = 'n', keys = '`' },
  { mode = 'x', keys = '`' },
  { mode = 'n', keys = '"' },
  { mode = 'x', keys = '"' },
  { mode = 'i', keys = '<C-r>' },
  { mode = 'c', keys = '<C-r>' },
  { mode = 'n', keys = '<C-w>' },
  { mode = 'n', keys = 'z' },
  { mode = 'x', keys = 'z' },
}
